var gamePieces = new Array("Rock", "Paper", "Scissors", "Dynamite");
var userMove = "";
var computerMove = "";
var randomNumber = 0;
        
function startGame(){

    //prompt user for their move
    userMove = prompt("What do you choose? Rock, Paper, Scissors or Dynamite? Be sure to capitalize your choice (ie: \"Rock\" instead of \"rock\")");

    //print user's choice to the screen
    document.getElementById("userMoveText").innerHTML = userMove;

    //Generate computer's move
        function getRandomGamePiece(){

            //create random number based on length of gamePieces array
            randomNumber = Math.floor((Math.random()*gamePieces.length)+0);

            //pass in randomly generated number, and based on that number, assign a value to
            //the computerMove variable
            switch (randomNumber)
            {
                case 0:
                    computerMove = "Rock";
                    break;
                case 1:
                    computerMove = "Paper";
                    break;
                case 2:
                    computerMove = "Scissors";
                    break;
                case 3:
                    computerMove = "Dynamite";
                    break;
            }
            
            //print computer's move to the screen
            document.getElementById("computerMoveText").innerHTML = computerMove;
            
            }

            //call function to calculate computer's move
            getRandomGamePiece();

            //whoWins function compares userMove and computerMove variables to determine winner
            function whoWins(){
            
            if(userMove == computerMove){ //if both moves match, print tie message
                document.getElementById("winnerText").innerHTML = "Tie";
                    
            }else if(userMove == "Rock"){ //if user selected Rock, compare against computerMove value

                if(computerMove == "Paper"){
                    document.getElementById("winnerText").innerHTML = "The computer wins.";
                }else if(computerMove == "Scissors"){
                    document.getElementById("winnerText").innerHTML = "The user wins.";
                }else{ //if computer is dynamite
                    document.getElementById("winnerText").innerHTML = "The computer wins.";
                }

            }else if(userMove == "Paper"){ //if user selected Paper, compare against computerMove value

                if(computerMove == "Rock"){
                    document.getElementById("winnerText").innerHTML = "The user wins.";
                }else if(computerMove == "Scissors"){
                    document.getElementById("winnerText").innerHTML = "The computer wins.";
                }else{ //if computer is dynamite
                    document.getElementById("winnerText").innerHTML = "The computer wins.";
                }

            } else if(userMove == "Scissors"){ //if user selected Scissors, compare against computerMove value

                if(computerMove == "Rock"){
                    document.getElementById("winnerText").innerHTML = "The computer wins.";
                }else if(computerMove == "Paper"){
                    document.getElementById("winnerText").innerHTML = "The user wins.";
                }else{
                    document.getElementById("winnerText").innerHTML = "The user wins.";
                }

            }else{ //assume dynamite was entered by user, and compare against computerMove value

                if(computerMove == "Rock"){
                    document.getElementById("winnerText").innerHTML = "The user wins.";
                }else if(computerMove == "Paper"){
                    document.getElementById("winnerText").innerHTML = "The user wins.";
                }else{ //assume scissors was generated by computer
                    document.getElementById("winnerText").innerHTML = "The computer wins.";
                }
            }
            
        }
            //call who Wins function to calculate winner
            whoWins();
        }