//declare global variables
var gamePieces = new Array("ROCK", "PAPER", "SCISSORS", "DYNAMITE");
var userMove = "";
var computerMove = "";
var randomNumber = 0;

/*startGame function will:
- Prompt user for move, uppercase and clean user's entry, and prints user's move to screen.
- Call an internal function named getRandomGamePiece, which uses a randomly generated number to determine the computer's move
- Prints computer's move to the screen and calls the whoWins function to compare the moves to determine the winner
*/
function startGame(){

    //prompt user for their move
    userMove = prompt("What do you choose? Rock, Paper, Scissors or Dynamite?");
    
    //remove spaces, if any, from user's input
    userMove = userMove.trim();
    
    //make user's entry upper case
    userMove = userMove.toUpperCase();

    //print user's choice to the screen
    document.getElementById("userMoveText").innerHTML = userMove;


        //Generate computer's move
        function getRandomGamePiece(){

            //create random number based on length of gamePieces array
            randomNumber = Math.floor((Math.random()*gamePieces.length)+0);

            //pass in randomly generated number, and based on that number, assign a value to
            //the computerMove variable
            switch (randomNumber){
                case 0:
                    computerMove = "ROCK";
                    break;
                case 1:
                    computerMove = "PAPER";
                    break;
                case 2:
                    computerMove = "SCISSORS";
                    break;
                case 3:
                    computerMove = "DYNAMITE";
                    break;
            }
            
            //print computer's move to the screen
            document.getElementById("computerMoveText").innerHTML = computerMove;
            
            }

            //call function to calculate computer's move
            getRandomGamePiece();

            //whoWins function compares userMove and computerMove variables to determine winner
            function whoWins(){
            
            if(userMove == computerMove){ //if both moves match, print tie message
                document.getElementById("winnerText").innerHTML = "Tie";
                    
            }else if(userMove == "ROCK"){ //if user selected Rock, compare against computerMove value

                if(computerMove == "PAPER"){
                    document.getElementById("winnerText").innerHTML = "The computer wins.";
                }else if(computerMove == "SCISSORS"){
                    document.getElementById("winnerText").innerHTML = "The user wins.";
                }else{ //if computer is dynamite
                    document.getElementById("winnerText").innerHTML = "The computer wins.";
                }

            }else if(userMove == "PAPER"){ //if user selected Paper, compare against computerMove value

                if(computerMove == "ROCK"){
                    document.getElementById("winnerText").innerHTML = "The user wins.";
                }else if(computerMove == "SCISSORS"){
                    document.getElementById("winnerText").innerHTML = "The computer wins.";
                }else{ //if computer is dynamite
                    document.getElementById("winnerText").innerHTML = "The computer wins.";
                }

            } else if(userMove == "SCISSORS"){ //if user selected Scissors, compare against computerMove value

                if(computerMove == "ROCK"){
                    document.getElementById("winnerText").innerHTML = "The computer wins.";
                }else if(computerMove == "PAPER"){
                    document.getElementById("winnerText").innerHTML = "The user wins.";
                }else{
                    document.getElementById("winnerText").innerHTML = "The user wins.";
                }

            }else{ //assume dynamite was entered by user, and compare against computerMove value

                if(computerMove == "ROCK"){
                    document.getElementById("winnerText").innerHTML = "The user wins.";
                }else if(computerMove == "PAPER"){
                    document.getElementById("winnerText").innerHTML = "The user wins.";
                }else{ //assume scissors was generated by computer
                    document.getElementById("winnerText").innerHTML = "The computer wins.";
                }
            }
            
        }
            //call who Wins function to calculate winner
            whoWins();
        }